/**
 * Jira Import Script for Brandastic PM
 * 
 * This script imports tickets from Jira CSV or JSON exports into Supabase.
 * 
 * Usage:
 *   1. Export your Jira issues as CSV or JSON
 *   2. Set your Supabase credentials in .env
 *   3. Run: node scripts/import.js <path-to-file> <board-id> <client-id>
 * 
 * Example:
 *   node scripts/import.js ./jira-export.csv abc123-board-id xyz789-client-id
 */

import { createClient } from '@supabase/supabase-js'
import fs from 'fs'
import path from 'path'

// Load environment variables (you may need to adjust for your setup)
const SUPABASE_URL = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Error: Missing Supabase credentials.')
  console.error('Please set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables.')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY)

/**
 * Parse Jira CSV file
 */
function parseCSV(content) {
  const lines = content.split('\n')
  if (lines.length < 2) {
    throw new Error('CSV file is empty or has no data rows')
  }

  // Parse header
  const header = parseCSVLine(lines[0])
  const issues = []

  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue
    
    const values = parseCSVLine(lines[i])
    const issue = {}
    
    header.forEach((key, index) => {
      issue[key.trim()] = values[index]?.trim() || ''
    })
    
    issues.push(issue)
  }

  return issues
}

/**
 * Parse a single CSV line handling quoted values
 */
function parseCSVLine(line) {
  const result = []
  let current = ''
  let inQuotes = false

  for (let i = 0; i < line.length; i++) {
    const char = line[i]
    
    if (char === '"') {
      inQuotes = !inQuotes
    } else if (char === ',' && !inQuotes) {
      result.push(current)
      current = ''
    } else {
      current += char
    }
  }
  result.push(current)
  
  return result
}

/**
 * Parse Jira JSON file
 */
function parseJSON(content) {
  const data = JSON.parse(content)
  
  // Handle different JSON export formats
  if (Array.isArray(data)) {
    return data
  } else if (data.issues) {
    return data.issues
  } else {
    throw new Error('Unrecognized JSON format')
  }
}

/**
 * Map Jira status to Brandastic status
 */
function mapStatus(jiraStatus) {
  const status = jiraStatus?.toLowerCase() || ''
  
  if (['done', 'closed', 'resolved', 'complete'].some(s => status.includes(s))) {
    return 'done'
  }
  if (['in progress', 'in development', 'in review', 'testing'].some(s => status.includes(s))) {
    return 'inprogress'
  }
  return 'todo'
}

/**
 * Map Jira priority to Brandastic priority
 */
function mapPriority(jiraPriority) {
  const priority = jiraPriority?.toLowerCase() || ''
  
  if (['highest', 'blocker', 'critical'].some(p => priority.includes(p))) {
    return 'urgent'
  }
  if (['high'].some(p => priority.includes(p))) {
    return 'high'
  }
  if (['low', 'lowest', 'trivial'].some(p => priority.includes(p))) {
    return 'low'
  }
  return 'medium'
}

/**
 * Transform Jira issue to Brandastic ticket
 */
function transformIssue(issue, boardId, clientId, position) {
  // Handle both CSV and JSON field names
  const getField = (...names) => {
    for (const name of names) {
      if (issue[name]) return issue[name]
      // Also check nested fields structure (JSON export)
      if (issue.fields && issue.fields[name]) return issue.fields[name]
    }
    return ''
  }

  return {
    title: getField('Summary', 'summary', 'Issue Summary') || 'Imported Ticket',
    description: getField('Description', 'description') || '',
    board_id: boardId,
    client_id: clientId,
    status: mapStatus(getField('Status', 'status', 'Issue Status')),
    priority: mapPriority(getField('Priority', 'priority')),
    tags: extractTags(getField('Labels', 'labels', 'Components')),
    estimated_hours: parseEstimate(getField('Original Estimate', 'timeoriginalestimate', 'Time Estimate')),
    position: position,
    // Note: ticket_id will be auto-generated by the database trigger
  }
}

/**
 * Extract tags from comma-separated string or array
 */
function extractTags(value) {
  if (!value) return []
  if (Array.isArray(value)) return value.map(t => t.name || t).filter(Boolean)
  return value.split(',').map(t => t.trim()).filter(Boolean)
}

/**
 * Parse Jira time estimate to hours
 */
function parseEstimate(value) {
  if (!value) return null
  
  // Handle seconds (JSON export)
  if (typeof value === 'number') {
    return Math.round(value / 3600 * 10) / 10
  }
  
  // Handle string formats like "2h", "1d 4h", etc.
  let hours = 0
  const dayMatch = value.match(/(\d+)d/)
  const hourMatch = value.match(/(\d+)h/)
  const minMatch = value.match(/(\d+)m/)
  
  if (dayMatch) hours += parseInt(dayMatch[1]) * 8 // 8-hour work day
  if (hourMatch) hours += parseInt(hourMatch[1])
  if (minMatch) hours += parseInt(minMatch[1]) / 60
  
  return hours > 0 ? Math.round(hours * 10) / 10 : null
}

/**
 * Main import function
 */
async function importFromJira(filePath, boardId, clientId) {
  console.log('\n🚀 Starting Jira import...\n')
  
  // Validate inputs
  if (!filePath || !boardId || !clientId) {
    console.error('Usage: node import.js <file-path> <board-id> <client-id>')
    process.exit(1)
  }

  // Read file
  const fullPath = path.resolve(filePath)
  if (!fs.existsSync(fullPath)) {
    console.error(`Error: File not found: ${fullPath}`)
    process.exit(1)
  }

  const content = fs.readFileSync(fullPath, 'utf-8')
  const ext = path.extname(filePath).toLowerCase()

  // Parse file
  let issues
  try {
    if (ext === '.csv') {
      console.log('📄 Parsing CSV file...')
      issues = parseCSV(content)
    } else if (ext === '.json') {
      console.log('📄 Parsing JSON file...')
      issues = parseJSON(content)
    } else {
      throw new Error(`Unsupported file format: ${ext}. Use .csv or .json`)
    }
  } catch (error) {
    console.error(`Error parsing file: ${error.message}`)
    process.exit(1)
  }

  console.log(`   Found ${issues.length} issues to import\n`)

  // Verify board and client exist
  const { data: board, error: boardError } = await supabase
    .from('boards')
    .select('id, name')
    .eq('id', boardId)
    .single()

  if (boardError || !board) {
    console.error(`Error: Board not found with ID: ${boardId}`)
    process.exit(1)
  }

  const { data: client, error: clientError } = await supabase
    .from('clients')
    .select('id, name')
    .eq('id', clientId)
    .single()

  if (clientError || !client) {
    console.error(`Error: Client not found with ID: ${clientId}`)
    process.exit(1)
  }

  console.log(`📋 Importing to board: ${board.name}`)
  console.log(`👥 For client: ${client.name}\n`)

  // Transform issues to tickets
  const tickets = issues.map((issue, index) => 
    transformIssue(issue, boardId, clientId, index)
  )

  // Import in batches
  const batchSize = 50
  let imported = 0
  let failed = 0

  console.log('⏳ Importing tickets...\n')

  for (let i = 0; i < tickets.length; i += batchSize) {
    const batch = tickets.slice(i, i + batchSize)
    
    const { data, error } = await supabase
      .from('tickets')
      .insert(batch)
      .select('ticket_id, title')

    if (error) {
      console.error(`   ❌ Batch ${Math.floor(i / batchSize) + 1} failed:`, error.message)
      failed += batch.length
    } else {
      imported += data.length
      data.forEach(t => {
        console.log(`   ✅ ${t.ticket_id}: ${t.title.substring(0, 50)}${t.title.length > 50 ? '...' : ''}`)
      })
    }
  }

  // Summary
  console.log('\n' + '='.repeat(50))
  console.log('📊 Import Summary')
  console.log('='.repeat(50))
  console.log(`   Total issues:    ${issues.length}`)
  console.log(`   ✅ Imported:     ${imported}`)
  console.log(`   ❌ Failed:       ${failed}`)
  console.log('='.repeat(50) + '\n')

  if (imported > 0) {
    console.log(`🎉 Success! View your imported tickets at:`)
    console.log(`   /boards/${boardId}\n`)
  }
}

// Run the import
const args = process.argv.slice(2)
importFromJira(args[0], args[1], args[2])
